fix(ark-metadata): save raw_metadata
ArkProjectNFTs/ark-project pull request #154
Opened 2023-10-20 12:28 UTC by remiroyc

## Description

Resolved an issue with metadata request and serialization.

## What type of PR is this? (check all applicable)

- [X] 🐛 Bug Fix (`fix:`)

## Related Tickets & Documents

## Added tests?

- [X] 👍 yes

## Added to documentation?

- [X] 🙅 no documentation needed

2023-10-20 17:06 UTC, glihm requested changes

2023-10-20 17:06 UTC, glihm commented on crates/ark-metadata/src/types.rs
> +    pub metadata: NormalizedMetadata,
```suggestion
    pub raw: String,
    pub normalized: NormalizedMetadata,
```

2023-10-20 17:06 UTC, glihm commented on crates/ark-metadata/src/utils.rs
> +            info!("Fetching metadata from IPFS: {}", complete_uri.as_str());
```suggestion
            trace!("Fetching metadata from IPFS: {}", complete_uri.as_str());
```

2023-10-20 17:06 UTC, glihm commented on crates/ark-metadata/src/utils.rs
> +            info!("Fetching metadata from HTTPS: {}", uri.as_str());
```suggestion
            trace!("Fetching metadata from HTTPS: {}", uri.as_str());
```

2023-10-20 17:06 UTC, glihm commented on crates/ark-metadata/src/utils.rs
> +            info!("Fetching on-chain metadata: {}", uri);
```suggestion
            trace!("Fetching on-chain metadata: {}", uri);
```

2023-10-23 10:04 UTC, kwiss approved these changes

2023-10-23 10:06 UTC, merged